package com.aresstack.askai.importing;

import com.aresstack.askai.catalog.OllamaModelImportProfile;
import com.aresstack.askai.client.OllamaCreateModelRequest;
import com.aresstack.askai.util.JsonSupport;
import com.aresstack.windirectml.workbench.download.ModelDownloadManifest;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Owns the visible AskAI model directory layout independently from Ollama's blob cache.
 */
public final class AskAiModelStore {

    private static final Pattern NUMBER_PARAMETER = Pattern.compile("\\\"([^\\\"]+)\\\"\\s*:\\s*([-+0-9.]+)");
    private static final Pattern STOP_ARRAY = Pattern.compile("\\\"stop\\\"\\s*:\\s*\\[(.*?)\\]");
    private static final Pattern JSON_STRING = Pattern.compile("\\\"((?:\\\\.|[^\\\\\\\"])*)\\\"");

    public AskAiModelInstallation installationFor(Path modelRoot, ModelDownloadManifest manifest) {
        return new AskAiModelInstallation(manifest.modelId(), modelRoot.resolve(manifest.localDirName()));
    }

    public void prepareInstallation(AskAiModelInstallation installation) throws IOException {
        Files.createDirectories(installation.getSourceDirectory());
        Files.createDirectories(installation.getOllamaDirectory());
    }

    public void writeOllamaArtifacts(AskAiModelInstallation installation, OllamaCreateModelRequest request,
                                     OllamaImportPlan plan) throws IOException {
        prepareInstallation(installation);
        writeText(installation.getModelfile(), modelfileFor(installation, plan));
        writeText(installation.getCreateRequestFile(), request.toPrettyJson());
        writeText(installation.getInstallMetadataFile(), installMetadataFor(installation, plan));
    }

    private static void writeText(Path path, String text) throws IOException {
        Files.write(path, text.getBytes(StandardCharsets.UTF_8));
    }

    private String modelfileFor(AskAiModelInstallation installation, OllamaImportPlan plan) {
        StringBuilder builder = new StringBuilder();
        builder.append("# Generated by AskAI.\n");
        builder.append("# Ollama still stores final layers in its internal blob cache.\n");
        builder.append("# This file documents the visible model installation that AskAI manages.\n\n");
        builder.append("FROM ").append(modelfilePath(installation.getSourceDirectory())).append("\n\n");

        OllamaModelImportProfile profile = plan.getImportProfile();
        if (profile.hasTemplate()) {
            builder.append("TEMPLATE \"\"\"\n");
            builder.append(profile.getTemplate()).append("\n");
            builder.append("\"\"\"\n\n");
        }
        if (profile.hasSystemPrompt()) {
            builder.append("SYSTEM \"\"\"\n");
            builder.append(profile.getSystemPrompt()).append("\n");
            builder.append("\"\"\"\n\n");
        }
        appendParameters(builder, profile.getParametersJson());
        return builder.toString();
    }

    private void appendParameters(StringBuilder builder, String parametersJson) {
        if (parametersJson == null || parametersJson.trim().isEmpty()) {
            return;
        }
        Matcher numericMatcher = NUMBER_PARAMETER.matcher(parametersJson);
        while (numericMatcher.find()) {
            String name = numericMatcher.group(1);
            if (!"stop".equals(name)) {
                builder.append("PARAMETER ").append(name).append(' ').append(numericMatcher.group(2)).append("\n");
            }
        }
        for (String stopToken : extractStopTokens(parametersJson)) {
            builder.append("PARAMETER stop ").append(modelfileString(stopToken)).append("\n");
        }
    }

    private List<String> extractStopTokens(String parametersJson) {
        ArrayList<String> tokens = new ArrayList<String>();
        Matcher arrayMatcher = STOP_ARRAY.matcher(parametersJson);
        if (!arrayMatcher.find()) {
            return tokens;
        }
        Matcher stringMatcher = JSON_STRING.matcher(arrayMatcher.group(1));
        while (stringMatcher.find()) {
            tokens.add(unescapeJsonString(stringMatcher.group(1)));
        }
        return tokens;
    }

    private String installMetadataFor(AskAiModelInstallation installation, OllamaImportPlan plan) {
        StringBuilder builder = new StringBuilder();
        builder.append("{\n");
        appendJsonField(builder, "modelId", installation.getModelId(), true);
        appendJsonField(builder, "ollamaModelName", plan.getOllamaModelName(), true);
        appendJsonField(builder, "profile", plan.getImportProfile().getDisplayName(), true);
        appendJsonField(builder, "quantization", plan.getQuantization(), true);
        appendJsonField(builder, "sourceDirectory", installation.getSourceDirectory().toString(), true);
        appendJsonField(builder, "ollamaDirectory", installation.getOllamaDirectory().toString(), true);
        appendJsonField(builder, "createdAt", Instant.now().toString(), false);
        builder.append("}\n");
        return builder.toString();
    }

    private static void appendJsonField(StringBuilder builder, String name, String value, boolean comma) {
        builder.append("  ").append(JsonSupport.quote(name)).append(": ").append(JsonSupport.quote(value));
        if (comma) {
            builder.append(',');
        }
        builder.append("\n");
    }

    private static String modelfilePath(Path path) {
        return modelfileString(path.toAbsolutePath().normalize().toString().replace('\\', '/'));
    }

    private static String modelfileString(String value) {
        String escaped = value.replace("\\", "\\\\").replace("\"", "\\\"");
        return "\"" + escaped + "\"";
    }

    private static String unescapeJsonString(String value) {
        return JsonSupport.extractFirstStringValue("{\"value\":\"" + value + "\"}", "value");
    }
}
